apiVersion: v1
kind: Service
metadata:
  name: fargate-mutating-webhook
  namespace: fargate-scale-webhook
spec:
  selector:
    app: fargate-mutating-webhook
  ports:
    - port: 443
      targetPort: tls
      name: application
    - port: 80
      targetPort: metrics
      name: metrics